---
title: "Exploratory_FA"
author: "S/18/834"
date: "2024-04-05"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(corrplot)
library(psych)
library(lavaan)
library(ggplot2)
library(factoextra)
library(semPlot)
library(ggcorrplot)
```

```{r}
dow_jones_data <- read_csv("../Data/dow_jones_index.csv")

new_names <- c(
  "quarter" = "quarter",
  "stock" = "stock",
  "date" = "date",
  "open" = "open",
  "high" = "high",
  "low" = "low",
  "close" = "close",
  "volume" = "volume",
  "percent_change_price" = "PCP",
  "percent_change_volume_over_last_wk" = "PCVLW",
  "previous_weeks_volume" = "PWV",
  "next_weeks_open" = "NWO",
  "next_weeks_close" = "NWC",
  "percent_change_next_weeks_price" = "PCPNW",
  "days_to_next_dividend" = "DD",
  "percent_return_next_dividend" = "PRND"
)

colnames(dow_jones_data) <- new_names

```

```{r}
dow_jones_data<-na.omit(dow_jones_data)

```

```{r}
dow_jones_data <- dow_jones_data %>%
                   mutate(NWC = as.numeric(gsub("\\$", "", NWC)))

dow_jones_data <- dow_jones_data %>%
                   mutate(NWO = as.numeric(gsub("\\$", "", NWO)))

dow_jones_data <- dow_jones_data %>%
                   mutate(open = as.numeric(gsub("\\$", "", open)))

dow_jones_data <- dow_jones_data %>%
                   mutate(high = as.numeric(gsub("\\$", "", high)))

dow_jones_data <- dow_jones_data %>%
                   mutate(low = as.numeric(gsub("\\$", "", low)))

dow_jones_data <- dow_jones_data %>%
                   mutate(close = as.numeric(gsub("\\$", "", close)))

dow_jones_data$quarter<-as.numeric(dow_jones_data$quarter)
dow_jones_data$stock<-as.factor(dow_jones_data$stock)
dow_jones_data$date <- as.Date(dow_jones_data$date,format= "%m/%d/%Y")
#dow_jones_data$date <- as.numeric(dow_jones_data$date)


```


```{r}
str(dow_jones_data)
```
```{r}
# Shorten variable names by selecting first letters of two words
#colnames(dow_jones_data) <- gsub("\\b(\\w)\\w*\\W*\\s*(\\w)\\w*\\W*", "\\1\\2", #colnames(dow_jones_data))

dow_jones<-dow_jones_data[,-(1:3)]

normalized_data<-scale(dow_jones)
#KMO test
KMO(r=dow_jones)
KMO(r=normalized_data)

#Bartletts Test
cortest.bartlett(dow_jones)
cortest.bartlett(normalized_data)


dow_jones_1<-dow_jones[,-c(1,7,8,12)]
KMO(r=dow_jones_1)

ggcorrplot::ggcorrplot(corr_norm)
```
```{r}
eigen_norm<-eigen(corr_norm)
eigen_values_norm<-eigen_norm$values
eigen_values_norm
eigen_values_norm<-round(eigen_values_norm, digits = 4)

cor_matrix<-cor(dow_jones)
corrplot(cor_matrix,method="square",tl.col = "black")

corr_norm<-cor(normalized_data)
corrplot(corr_norm)

dim(cor_matrix)

#efa_result<-fa(cor_matrix,nfactors = 10,rotate = "none")
#efa_result
#eigen_values<-efa_result$values
#eigen_values


#KMO(r=normalized_data)
#corr_norm<-cor(normalized_data)
#dim(cor_matrix)

efa_result_norm<-fa(corr_norm,nfactors = 13,rotate = "none")
efa_result_norm
eigen_values_norm<-efa_result$values
eigen_values_norm

num_factors_kaiser_norm<-sum(eigen_values_norm>1)
num_factors_kaiser_norm

ggcorplot
```


```{r}
eignvalues<-eigen(cor_matrix)$values
eignvalues

eign_values_norm<-eigen(corr_norm)$values
eigen_values_norm


num_factors_kaiser<-sum(eigen_values_norm>1)
num_factors_kaiser

num_factors_kaiser_norm<-sum(eigen_values_norm>1)
num_factors_kaiser_norm

var_explained=(eignvalues/sum(eignvalues)) 
var_explained

var_explained_norm=(eign_values_norm/sum(eign_values_norm)) 
round(var_explained_norm,digits = 4)
```

```{r}
scree(dow_jones)

scree(normalized_data)
```

```{r}
#parallel Analysis from Scree plots
fa.parallel(dow_jones,fm="pa",fa="fa")
fa.parallel(normalized_data,fm="pa",fa="fa")
```

```{r}
#Factor analysis from PA method
dw_pca<-princomp(cor_matrix)
dw_pca
summary(dw_pca)


dow_jones_PCA<-fa(cor_matrix,nfactors = 5,rotate = "varimax",n.obs = 720,cor=TRUE,fm="pa",max.iter = 1000,scores = "regression")
dow_jones_PCA

pca_norm<-fa(corr_norm,nfactors = 4,rotate = "varimax",n.obs = 720,cor=TRUE,fm="pa",max.iter = 1000,scores = "regression")
pca_norm

#normalized_PCA<-fa(corr_norm,nfactors = 5,rotate = "varimax",n.obs = 720,cor=TRUE,fm="pa",max.iter = 1000,scores = "regression")
#normalized_PCA

#promax
#promax_pca <- fa(cor_matrix, nfactors = 5, rotate = "promax", n.obs = 720, cor = TRUE, fm = "pa",max.iter = 1000,scores = "regression")
#promax_pca

#oblique
#oblique_PCA <- fa(cor_matrix, nfactors = 5, rotate = "oblimin", n.obs = 720, cor = TRUE, fm = "pa",scores = "regression",max.iter = 1500)
#oblique_PCA

#oblimin
#oblimin_PCA <- fa(cor_matrix, nfactors = 5, rotate = "oblimin", n.obs = 720, cor = TRUE, fm = "pa", oblique.scores = TRUE,scores = "regression",max.iter = 1000)
#oblimin_PCA


```


```{r}
#unrotated loadings for PCA
unrotated_pc_loadings <-as.data.frame(unclass(pca_norm$loadings))
unrotated_pc_loadings

pc_loadings_norm <-as.data.frame(unclass(pca_norm$loadings))
pc_loadings_norm

```

```{r}
#communalities
unrotated_pc_com <- as.data.frame(unclass(dow_jones_PCA$communality))
unrotated_pc_com


rotated_pc_com<-as.data.frame(dow_jones_PCA$communality)
rotated_pc_com

pc_com_norm <- as.data.frame(unclass(pca_norm$communality))
pc_com_norm

pc_com_norm_rotated<-as.data.frame(pca_norm$communality)
pc_com_norm_rotated
```


```{r}
#normality test
shapiro.test(dow_jones$on)
shapiro.test(dow_jones$hh)
shapiro.test(quantitative_dow_jones$lw)
shapiro.test(quantitative_dow_jones$ce)
shapiro.test(quantitative_dow_jones$ve)
shapiro.test(quantitative_dow_jones$pe)
shapiro.test(quantitative_dow_jones$pk)
shapiro.test(quantitative_dow_jones$nn)
shapiro.test(quantitative_dow_jones$ne)
shapiro.test(quantitative_dow_jones$pd)

```

```{r}
#FA with ML
dow_jones_ML <- fa(cor_matrix,nfactors = 4,rotate = "varimax",n.obs = 720 , corr = TRUE, fm = 'ml')
dow_jones_ML
dow_jones_ML$loadings

#communalities
dow_jones_ml_com<-as.data.frame(dow_jones_ML$communality)
dow_jones_ml_com

#unrotated
dow_jones_ml_com<-as.data.frame(unclass(dow_jones_ML$communality))
dow_jones_ml_com

#FA with ML
ml_norm <- fa(corr_norm,nfactors = 5,rotate = "varimax",n.obs = 720 , corr = TRUE, fm = 'ml')
ml_norm

#communalities
ml_Norm_com<-as.data.frame(ml_norm$communality)
ml_Norm_com

#unrotated
dow_jones_ml_com<-as.data.frame(unclass(dow_jones_ML$communality))
dow_jones_ml_com

```

```{r}
#factor diagram
fa.diagram(dow_jones_ML)
fa.diagram(dow_jones_PCA)

#factor diagram
fa.diagram(ml_norm)
fa.diagram(pca_norm)
```



```{r}
jow_dones_data_fa<-factanal(normalized_data,factors=4)
jow_dones_data_fa

biplot(jow_dones_data_fa)
```

```{r}
variables <-normalized_data[,-12]

cov(variables)

any(is.na(variables))

#define the CFA model
model <- '
 Factor1 =~ open+high+low+close+NWO+NWC
 Factor2 =~ volume+PWV+PRND
 Factor3 =~ PCVLW
 Factor4 =~ PCPNW
'
# Fit the CFA model
#fit <- cfa(model, data = variables)

fit1<-sem(model,data = variables)

# Assess model fit
#summary(fit, fit.measures = TRUE)
summary(fit1,fit.measures=TRUE,standardized=TRUE)


semPlot::semPaths(fit1,"std")
semPaths(fit1, what = "col", whatLabels = "std", style = "mx", rotation = 1,
    layout = "tree", nCharNodes = 8, shapeMan = "rectangle", sizeMan = 9, sizeMan2 = 5,edge.color="blue")




# Standardized estimates (factor loadings)
parameterEstimates(fit, standardized = TRUE, ci = TRUE)
```


